name: vozdosastrosproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  url_launcher: ^6.2.6
  flutter_svg: ^2.0.10
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/voz_dos_astros_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/bg_default.png
    - assets/backgrounds/bg_aries.png
    - assets/backgrounds/bg_touro.png
    - assets/backgrounds/bg_gemeos.png
    - assets/backgrounds/bg_cancer.png
    - assets/backgrounds/bg_leao.png
    - assets/backgrounds/bg_virgem.png
    - assets/backgrounds/bg_libra.png
    - assets/backgrounds/bg_escorpiao.png
    - assets/backgrounds/bg_sagitario.png
    - assets/backgrounds/bg_capricornio.png
    - assets/backgrounds/bg_aquario.png
    - assets/backgrounds/bg_peixes.png
    - assets/horoscopos_maio_2025.json
    - assets/horoscopos_junho_2025.json
    - assets/horoscopos_julho_2025.json
    - assets/horoscopos_agosto_2025.json
    - assets/icons/
